[platformio]
default_envs = esp32s3-qemu-spi2

[env:esp32s3-qemu-spi2]
platform = espressif32 @ 7.0.1
board = esp32-s3-devkitc-1
framework = espidf
board_build.flash_size = 8MB
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
