[platformio]
src_dir = firmware/src
lib_extra_dirs = lib

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5Unified @ 0.2.19
build_flags =
  -DCORE_DEBUG_LEVEL=3
